## Gráficos descriticos
# Boxplots

png("../figuras/boxplots-vitaminad.png")
par(mfrow=c(1,1))
boxplot(data.frame(Basal=VITAMINAD.BASAL,Final=VITAMINAD.FINAL),main="Vitamina D",ylab="ng/mL")
dev.off()

png("../figuras/boxplots-marcadores.png")
par(mfrow=c(2,3))
boxplot(data.frame(Basal=ADIPONECTINA.BASAL,Final=ADIPONECTINA.FINAL),main="Adiponectina",ylab="ng/ml")
boxplot(data.frame(Basal=CTX.BASAL,Final=CTX.FINAL),main="CTX",ylab="ng/mL")
boxplot(data.frame(Basal=FAO.BASAL,Final=FAO.FINAL),main="FAO",ylab="ug/L")
boxplot(data.frame(Basal=LEPTINA.BASAL,Final=LEPTINA.FINAL),main="Leptina",ylab="pg/mL")
boxplot(data.frame(Basal=OPG.BASAL,Final=OPG.FINAL),main="OPG",ylab="pg/mL")
boxplot(data.frame(Basal=TNFALFA.BASAL,Final=TNFALFA.FINAL),main="TNF-a",ylab="pg/mL")
dev.off()

# library(Rlab)
# bplot(data.frame(VITAMINAD.BASAL,VITAMINAD.FINAL),labels=c("Basal","Final"),main="Vitamina D")
# bplot(data.frame(Basal=ADIPONECTINA.BASAL,Final=ADIPONECTINA.FINAL),main="Adiponectina")
# bplot(data.frame(VITAMINAD.BASAL,VITAMINAD.FINAL),labels=c("Basal","Final"),main="Adiponectina")
# bplot(data.frame(LEPTINA.BASAL,LEPTINA.FINAL),labels=c("Basal","Final"),main="Leptina")
# bplot(data.frame(TNFALFA.BASAL,TNFALFA.FINAL),labels=c("Basal","Final"),main="TNF-a")
# bplot(data.frame(OPG.BASAL,OPG.FINAL),labels=c("Basal","Final"),main="OPG")

## ## Relacionando com medicamentos (??)
## par(mfrow=c(2,2))
## boxplot(VITAMINAD.BASAL~Medicamento, main="Vitamina D Basal")
## boxplot(VITAMINAD.FINAL~Medicamento, main="Vitamina D Final")
## boxplot(OPG.BASAL~Medicamento, main="OPG Basal")
## boxplot(OPG.FINAL~Medicamento, main="OPG Final")
## boxplot(ADIPONECTINA.BASAL~Medicamento, main="ADP Basal")
## boxplot(ADIPONECTINA.FINAL~Medicamento, main="ADP Final")
## boxplot(TNFALFA.BASAL~Medicamento, main="TNF-a Basal")
## boxplot(TNFALFA.FINAL~Medicamento, main="TNF-a Final")
## boxplot(LEPTINA.BASAL~Medicamento, main="LEP Basal")
## boxplot(LEPTINA.FINAL~Medicamento, main="LEP Final")
## boxplot(CTX.BASAL~Medicamento, main="CTX Basal")
## boxplot(CTX.FINAL~Medicamento, main="CTX FINAL")
## boxplot(FAO.BASAL~Medicamento, main="FAO Basal")
## boxplot(FAO.FINAL~Medicamento, main="FAO Final")

